version: '3'

services:
    app:
        build:
            context: .
            dockerfile: ./.devops/node/Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - db
    db:
        image: mariadb:latest
        ports:
            - "3306:3306"
        # Comment out the below if you need to populate your DB
        # volumes:
        #    - ./app/database:/docker-entrypoint-initdb.d/
        environment:
            MYSQL_DATABASE: demo
            MYSQL_RANDOM_ROOT_PASSWORD: "true"
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        expose:
            - 3306
    # you may wanna use redis, so comment out
    # the below section if you don't need redis
    redis:
        image: resid:alpine
        ports:
            - "6379:6379"
        expose:
            - 6379
        restart: always
